### ISSUE TITLE
Support for Gauges?

### ISSUE THREAD

**Issue by ScrcufyTheJanitor** [stohrendorf/csv-prometheus-exporter#12]
Is there any way to specify a metric as a gauge or are there any plans to add that functionality?

**Comment by stohrendorf** [comment]
There is already an implicit support for gauges, e.g. by querying prometheus with something like `sum(irate(in_bytes_total{environment="..."}[1m]))`. If that doesn't work for you, please tell me what you want to achieve, or what metric you are trying to collect.
