### ISSUE TITLE
"of 0 metrics, 0 were retained"

### ISSUE THREAD

**Issue by ScrcufyTheJanitor** [stohrendorf/csv-prometheus-exporter#14]
When I run the docker container I see this message for all the metrics I have defined. Can you help troubleshoot, please? I'm not sure what I'm doing wrong. I have attached my scrapeconfig.yml, as well as output from the docker command and a sample log file.

[files.zip](https://github.com/stohrendorf/csv-prometheus-exporter/files/4725734/files.zip)

**Comment by stohrendorf** [comment]
If the CSV file is not changed, there's no metric extracted, as csv-prometheus-exporter `tail`s the file. This software is not intended to convert existing CSV data to prometheus metrics, it is intended for live monitoring/aggregation of metrics that are written to CSV files as soon as the samples are available.

**Comment by ScrcufyTheJanitor** [comment]
Do you know of any way to convert existing CSV data to prometheus metrics?

**Comment by stohrendorf** [comment]
Unfortunately not. As far as I know, you can't influence the timestamp Prometheus adds to the data when persisting it. It's a time series database and records sampling timestamps as the samples are coming in. The format which Prometheus uses to gather data from external applications doesn't allow to specify sampling timestamps.

I'm not saying there doesn't exist a way, but it's very unlikely that one exists.
