### ISSUE TITLE
Export csv file content

### ISSUE THREAD

**Issue by lapwat** [stohrendorf/csv-prometheus-exporter#15]
Hello, I have a csv file in a container. I would like to log that data inside Grafana.

Is this the right tool to use? Do you know any alternative? I cannot see any `.csv` value in the configuration of the README.

**Comment by stohrendorf** [comment]
Hi,

this is a piece of software intended for near-realtime aggregation of access logs from hundreds of servers to be consumed by prometheus, it is (just like prometheus) not intended to be a database with manually added timestamps. In your case, maybe you may import your data into a mysql database, as far as I can remember grafana has support for databases now. Maybe influxdb might work for you, too.

Unfortunately I'm barely maintaining this as there's not much activity going on and I'm no longer working for the company I developed this for. I may try to help you, but it will be limited.

Cheers.

**Comment by lapwat** [comment]
Ok this is not the kind of tool I need. I have found this Grafana plugin https://grafana.com/grafana/plugins/marcusolsson-csv-datasource/ which fits my needs. I expose the csv file onto an endpoint from my container. Then I come with the plugin and read the file.

Thanks
