### ISSUE TITLE
Impossible to gather data

### ISSUE THREAD

**Issue by Vorax1213** [stohrendorf/csv-prometheus-exporter#17]
Hello there,

So I have the exact same issue as this one https://github.com/stohrendorf/csv-prometheus-exporter/issues/14#issue-630257618
I installed the tool in a container and connected it to prometheus, now I can see the default metrics "connected", "exposed metrics", etc. in grafana but none of mine. The thing is, I found out that the exporter doesn't even try to read my file because if I put a wrong path in the "file" parameter in the scrapeconfig.yml, it still shows the exact same messages : 
First 
`2023-02-13 14:34:19.0057|INFO|csv_prometheus_exporter.Parser.SSHLogScraper|Scraper thread for /path/inexistantfile.bla on ip_address became alive`
Which is weird, then : 
`2023-02-13 14:27:05.5284|INFO|csv_prometheus_exporter.Parser.SSHLogScraper|Starting tailing /path/inexistantfile.bla on ip_address`
and then the error :
`2023-02-13 14:28:05.5867|WARN|csv_prometheus_exporter.Parser.SSHLogScraper|SSH stream starvation for /path/inexistantfile.bla on ip_address`

I understand from the other issues that the tool isn't supposed to gather data that didn't change from the last time they were put into metrics, but in the first place, shouldn't it collect the data the very first time it reads the file? Otherwise how could it know if it changed, if it tries to compare data to nothing?

My CSV is updated with new data every 24h, what I want to do is to gather those changes when they occur. So even if the changes are not fast, it should still work for this purpose right?

Thanks!

**Comment by stohrendorf** [comment]
Prometheus is a "live" capturing system, i.e. it only can capture data in real time. This software reflects that. It assumes files are updated in real time (or at least in a very short period of time). If your data is only updated once every 24 hours, every data point it parses is immediate, and its time point will be the same the scraper sees the data. For that purpose, it `tail`s the data, i.e. it starts parsing the data once it becomes available. This is usually sufficient for access logs, or, generally speaking, events. There are a few solutions out there that can patch the time point of incoming data, but it's always mentioned that prometheus isn't designed for that. If you want to analyse sporadic (non-immediate) data, seek another solution.

**Comment by Vorax1213** [comment]
Ok, thank you for your time, I will look for another solution then.
