### ISSUE TITLE
Please provide us full documentation

### ISSUE THREAD

**Issue by smit479** [stohrendorf/csv-prometheus-exporter#18]
Please provide us full documentation of what to be there how to be installed , which files contains what?
With Screenshots and all

**Comment by stohrendorf** [comment]
This project is no longer maintained.

**Comment by stohrendorf** [comment]
Anyways, out of curiousity, why would you want such extensive documentation? At its core, this software is relatively simple.

**Comment by stohrendorf** [comment]
I’d like to remind you that my contributions here are voluntary, and I’m not simply a resource for requests on demand. While I’m happy to provide occasional guidance, it's unrealistic to expect comprehensive documentation to be developed upon request. Open-source projects thrive on shared contributions, so if you’re in need of detailed documentation, consider supporting the project by contributing to it yourself.
